### ISSUE TITLE
_fzf_orig_completion_g++: bad substitution

### ISSUE THREAD

**Issue by me-and** [me-and/Cygwin-fzf#3]
I've just upgraded my Cygwin installation, including a Bash upgrade, and now I'm getting the following error on starting a new Bash session:

    -bash: _fzf_orig_completion_g++: bad substitution

I haven't done any investigation into what might be going wrong here yet.

**Comment by mcooperman** [comment]
Windows 10
After doing a new install with Base package only, things were fine on launching the Cygwin terminal
After installing a complete list of packages I was interested in, I see the same message logged to the output of a new bash terminal, before the prompt is displayed.

poking around, i find the following link that may be relevant
https://github.com/junegunn/fzf/issues/668

my bash version
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)

my fzf version
fzf 0.8.9 (Dec 24, 2014)

the author says fzf support for cygwin discontinued w 0.9.0 due to issues w ncurses library
activity was indicated 20 days ago suggesting a workaround might be under development

the way i read all this is the reason for the error is the presence of the terminal part of the string, "...g++",  as the ..++ part comprises illegal characters in a name.

**Comment by gene-pavlovsky** [comment]
@mcooperman https://github.com/junegunn/fzf/issues/668#issuecomment-280023955
